project:
  type: website
  output-dir: docs

website:
  title: "Monetary Economics"
  page-navigation: true
  sidebar:
    style: floating
    contents:
      - index.qmd
      - section: "Topic 1 - The Nature and Economic Role of Money"
        contents:
          - text: "Reading"
            file: topic1reading.qmd
          - text: "Lecture"
            file: topic1lecture.qmd
          - text: "Questions"
            file: topic1questions.qmd
          - text: "MCQs"
            file: topic1mcqs.qmd
      - section: "Topic 2 - Classical Theory of Money"
        contents:
          - text: "Reading"
            file: topic2reading.qmd
          - text: "Lecture"
            file: topic2lecture.qmd
          - text: "MCQs"
            file: topic2tutorial.qmd
      - section: "Topic 3"
        contents:
          - text: "Reading"
            file: topic3reading.qmd
          - text: "Lecture"
            file: topic3lecture.qmd
          - text: "MCQs"
            file: topic3tutorial.qmd
      - section: "Topic 4"
        contents:
          - text: "Reading"
            file: topic4reading.qmd
          - text: "Lecture"
            file: topic4lecture.qmd
          - text: "MCQs"
            file: topic4tutorial.qmd
      - section: "Topic 5"
        contents:
          - text: "Reading"
            file: topic5reading.qmd
          - text: "Lecture"
            file: topic5lecture.qmd
          - text: "MCQs"
            file: topic5tutorial.qmd
      - section: "Topic 6"
        contents:
          - text: "Reading"
            file: topic6reading.qmd
          - text: "Lecture"
            file: topic6lecture.qmd
          - text: "MCQs"
            file: topic6tutorial.qmd
      - section: "Topic 7"
        contents:
          - text: "Reading"
            file: topic7reading.qmd
          - text: "Lecture"
            file: topic7lecture.qmd
          - text: "MCQs"
            file: topic7tutorial.qmd
      - section: "Topic 8"
        contents:
          - text: "Reading"
            file: topic8reading.qmd
          - text: "Lecture"
            file: topic8lecture.qmd
          - text: "MCQs"
            file: topic8tutorial.qmd
format:
  html:
    theme: litera
    number-sections: false
    code-copy: true
    code-overflow: wrap
    css:
      - styles.css
    html-math-method: mathjax
