project:
  type: website
  output-dir: docs

website:
  title: "Monetary Economics"
  page-navigation: true
  sidebar:
    style: floating
    contents:
      - index.qmd
      - section: "Topic 1 - The Nature and Economic Role of Money"
        contents:
          - text: "Reading"
            file: topic1reading.qmd
          - text: "Lecture"
            file: topic1lecture.qmd
          - text: "Questions"
            file: topic1questions.qmd
          - text: "MCQs"
            file: topic1mcqs.qmd
      - section: "Topic 2 - Classical Theory of Money"
        contents:
          - text: "Reading"
            file: topic2reading.qmd
          - text: "Lecture"
            file: topic2lecture.qmd
          - text: "MCQs"
            file: topic2mcqs.qmd
      - section: "Topic 3 - Keynes' Theory of Money"
        contents:
          - text: "Reading"
            file: topic3reading.qmd
          - text: "Lecture"
            file: topic3lecture.qmd
          - text: "MCQs"
            file: topic3mcqs.qmd
      - section: "Topic 4 - Friedman's Monetarism"
        contents:
          - text: "Reading"
            file: topic4reading.qmd
          - text: "Lecture"
            file: topic4lecture.qmd
          - text: "MCQs"
            file: topic4mcqs.qmd
      - section: "Topic 5 - The New Classical ApproachTheory of Money"
        contents:
          - text: "Reading"
            file: topic5reading.qmd
          - text: "Lecture"
            file: topic5lecture.qmd
          - text: "MCQs"
            file: topic5mcqs.qmd
      - section: "Topic 6 - The Time Inconsistency Problem and Credibility of Monetary Policy"
        contents:
          - text: "Reading"
            file: topic6reading.qmd
          - text: "Lecture"
            file: topic6lecture.qmd
          - text: "MCQs"
            file: topic6mcqs.qmd
      - section: "Topic 7 - The MOnetary Policy Consensus and the Great Moderation"
        contents:
          - text: "Reading"
            file: topic7reading.qmd
          - text: "Lecture"
            file: topic7lecture.qmd
          - text: "MCQs"
            file: topic7mcqs.qmd
      - section: "Topic 8 - Monetary Policy in the Post-Crisis"
        contents:
          - text: "Reading"
            file: topic8reading.qmd
          - text: "Lecture"
            file: topic8lecture.qmd
          - text: "MCQs"
            file: topic8mcqs.qmd
format:
  html:
    theme: litera
    number-sections: false
    code-copy: true
    code-overflow: wrap
    css:
      - styles.css
    html-math-method: mathjax
