project:
  type: website

website:
  title: "Monetary Economics EC3014"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: ec3014_week1_quiz.qmd
        text: "Week 1 Quiz"

format:
  html:
    toc: true
    theme: cosmo
