project:
  type: website
  output-dir: docs

website:
  title: "Monetary Economics"
  page-navigation: true
  sidebar:
    style: floating
    contents:
      - index.qmd
      - section: "Week 1"
        contents:
          - text: "Reading"
            file: week1reading.qmd
          - text: "Lecture"
            file: week1lecture.qmd
          - text: "Tutorial"
            file: week1tutorial.qmd

format:
  html:
    theme: litera
    number-sections: false
    code-copy: true
    code-overflow: wrap
    css:
      - styles.css
    html-math-method: mathjax
