project:
  type: website
  output-dir: _site

website:
  title: "Monetary Economics"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Lectures"
        href: lectures.qmd
      - text: "Labs"
        href: labs.qmd

format:
  html:
    theme: cosmo
    toc: true
