project:
  type: website
  output-dir: docs
website:
  title: "Monetary Economics EC3014"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: week1_quiz.qmd
        text: "Week 1 Quiz"

format:
  html:
    theme: litera
    number-sections: false
    code-copy: true
    code-overflow: wrap
    css:
      - styles.css
      - icons.css     # the new emoji polish
    html-math-method: mathjax
